#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server:

if ["$#" -lt 3]; then
    echo ""Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_Path="$1"
server_Ip="$2"
userName="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/ 

if [ "$?" -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Failed to transfer file"
fi
