#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect the requirements

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Create index.html with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null

# Configure nginx to use custom 404 page
sudo sed -i '/^\s*location \/ {/a \ \ \ \ error_page 404 /error_404.html;\n \ \ \ \ location = /error_404.html {\n \ \ \ \ \ \ \ \ internal;\n \ \ \ \ \ \ \ \ root /var/www/html;\n \ \ \ \ }' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
