#!/usr/bin/env bash
# Configure HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo bash -c 'echo "
frontend metoweb
    bind *:80
    mode http
    default_backend metoback
backend metoback
    balance roundrobin
    server 350396-web-01 54.237.93.225:80 check
    server 350396-web-02 54.172.137.10:80 check" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
