#!/usr/bin/env bash                                                             
# Create a script to create a mysql db backup and convert to tar.gz format usin\
# Script that generates a back up from a database
DATE=$(date +'%d-%m-%Y')
sudo mysqldump -u root -p "$1" -all-databases > backup.sql
tar -cvzf "$DATE".tar.gz backup.sql
