#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID

file=/var/run/myscript.pid

echo "$$" > $file

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm $file && exit' SIGQUITgit SIGTERM
done
