#!/usr/bin/env bash
# Manages 'manage_my_process'

file="/var/run/my_process.pid"
if [ "${1}" == "start" ]
then
	./manage_my_process &
	touch $file
	echo "$!" > $file
	echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
	echo "manage_my_process stopped"
	kill "$(cat $file)"
	rm $file
elif [ "${1}" == "restart" ]
then
	kill "$(cat $file)"
	rm $file
	./manage_my_process &
	touch $file
	echo "$!" > $file
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
