#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.


i=1
while [ $i -le 100 ]
do
	if (( i % 3 == 0))
	then
		printf "Fizz"
	fi
	if (( i % 5 == 0))
	then
		printf "Buzz"
	fi
	if (( i % 5 != 0 && i % 3 != 0))
	then
		printf "%s" "$i"
	fi

	printf "\n"
	((i++))
done
