#!/usr/bin/env bash
# set Nginx on user mode to run

pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/d\
efault
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
